# Generated by Django 2.2 on 2019-04-08 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('datemodified', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=255)),
                ('numberofcomment', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Blog',
                'db_table': 'Blog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bloguser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('confirmemail', models.PositiveSmallIntegerField(default=0)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bloguser',
                'db_table': 'Bloguser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('email', models.EmailField(max_length=75)),
                ('content', models.TextField()),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('blogid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='blogs.Blog')),
            ],
            options={
                'verbose_name_plural': 'Comment',
                'db_table': 'Comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('blogid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_image', to='blogs.Blog')),
            ],
            options={
                'verbose_name_plural': 'BlogImage',
                'db_table': 'BlogImage',
                'managed': True,
            },
        ),
    ]
