# Generated by Django 2.2 on 2019-04-08 05:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('barcode', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=60)),
                ('published_year', models.SmallIntegerField()),
                ('publication', models.CharField(max_length=60)),
                ('is_issue', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('mrp', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Books',
                'db_table': 'Books',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('enrollment_no', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('is_passed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('is_hostler', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('course', models.CharField(max_length=200)),
                ('course_type', models.CharField(choices=[('R', 'Regular'), ('D', 'Distance'), ('P', 'Part_Time')], max_length=1)),
                ('department', models.CharField(max_length=200)),
                ('course_duration', models.FloatField()),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('passing_year', models.SmallIntegerField(blank=True, null=True)),
                ('dob', models.CharField(help_text='dd/mm/yyyy', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Students',
                'db_table': 'Students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Checkouts',
            fields=[
                ('barcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='book_details', serialize=False, to='lms.Books')),
                ('issued_on', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2019, 5, 8, 11, 3, 15, 323770))),
                ('student_eno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_issued', to='lms.Students')),
            ],
            options={
                'verbose_name_plural': 'Checkouts',
                'db_table': 'Checkouts',
                'managed': True,
            },
        ),
    ]
